import {
  Activity,
  Anchor,
  Atom,
  Award,
  Axe,
  BadgeCheck,
  BarChart3,
  Bell,
  Bomb,
  BookOpen,
  Bot,
  Box,
  Brain,
  Briefcase,
  Brush,
  Bug,
  Cake,
  Calendar,
  Camera,
  Castle,
  Cat,
  CheckCircle2,
  Clock,
  Cloud,
  Code,
  Coffee,
  Coins,
  Compass,
  Cpu,
  Crown,
  Database,
  Diamond,
  Dog,
  Dumbbell,
  Eye,
  Feather,
  Film,
  Fingerprint,
  Fish,
  Flame,
  FlaskConical,
  Gamepad2,
  Gauge,
  Gem,
  Gift,
  Globe,
  GraduationCap,
  Hammer,
  Hand,
  Handshake,
  HardDrive,
  Headphones,
  Heart,
  Hexagon,
  Hourglass,
  Image,
  Infinity,
  Joystick,
  Key,
  Landmark,
  Laptop,
  Layers,
  Leaf,
  Lightbulb,
  Lock,
  Magnet,
  Mail,
  Map,
  Medal,
  Megaphone,
  MessageCircle,
  MessageSquare,
  Mic,
  Monitor,
  Moon,
  Mountain,
  Music,
  Navigation,
  Network,
  Orbit,
  Package,
  Paintbrush,
  Palette,
  Pencil,
  Phone,
  PiggyBank,
  Pizza,
  Plane,
  Plug,
  Printer,
  Puzzle,
  Rabbit,
  Radar,
  Radio,
  Recycle,
  RefreshCw,
  Rocket,
  Route,
  Scale,
  Scissors,
  Send,
  Server,
  Settings,
  Share2,
  Shield,
  ShieldCheck,
  Ship,
  Shirt,
  ShoppingBag,
  Skull,
  Smile,
  Snowflake,
  Sparkles,
  Sprout,
  Star,
  Sun,
  Sword,
  Swords,
  Tag,
  Target,
  Tent,
  Terminal,
  ThumbsUp,
  Ticket,
  Timer,
  Trees,
  TrendingUp,
  Trophy,
  Truck,
  Tv,
  Umbrella,
  UserPlus,
  Users,
  Video,
  Wallet,
  Wand2,
  Watch,
  Waves,
  Wifi,
  Wind,
  Wine,
  Wrench,
  Zap,
  type LucideIcon,
} from 'lucide-react';

// ────────────────────────────────────────────────────────────────
// Curated set of icons selectable in the admin panel by name.
// ────────────────────────────────────────────────────────────────

export const ICON_MAP: Record<string, LucideIcon> = {
  Activity, Anchor, Atom, Award, Axe, BadgeCheck, BarChart3, Bell, Bomb,
  BookOpen, Bot, Box, Brain, Briefcase, Brush, Bug, Cake, Calendar, Camera,
  Castle, Cat, CheckCircle2, Clock, Cloud, Code, Coffee, Coins, Compass, Cpu,
  Crown, Database, Diamond, Dog, Dumbbell, Eye, Feather, Film, Fingerprint,
  Fish, Flame, FlaskConical, Gamepad2, Gauge, Gem, Gift, Globe, GraduationCap,
  Hammer, Hand, Handshake, HardDrive, Headphones, Heart, Hexagon, Hourglass,
  Image, Infinity, Joystick, Key, Landmark, Laptop, Layers, Leaf, Lightbulb,
  Lock, Magnet, Mail, Map, Medal, Megaphone, MessageCircle, MessageSquare, Mic,
  Monitor, Moon, Mountain, Music, Navigation, Network, Orbit, Package,
  Paintbrush, Palette, Pencil, Phone, PiggyBank, Pizza, Plane, Plug, Printer,
  Puzzle, Rabbit, Radar, Radio, Recycle, RefreshCw, Rocket, Route, Scale,
  Scissors, Send, Server, Settings, Share2, Shield, ShieldCheck, Ship, Shirt,
  ShoppingBag, Skull, Smile, Snowflake, Sparkles, Sprout, Star, Sun, Sword,
  Swords, Tag, Target, Tent, Terminal, ThumbsUp, Ticket, Timer, Trees,
  TrendingUp, Trophy, Truck, Tv, Umbrella, UserPlus, Users, Video, Wallet,
  Wand2, Watch, Waves, Wifi, Wind, Wine, Wrench, Zap,
};

/** Resolve an icon name to a component, falling back to Sparkles. */
export function getIcon(name: string): LucideIcon {
  return ICON_MAP[name] ?? Sparkles;
}

/** Options for an icon picker, sorted alphabetically. */
export const ICON_OPTIONS = Object.keys(ICON_MAP)
  .sort((a, b) => a.localeCompare(b))
  .map((name) => ({ value: name, label: name }));
